repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: [ config, pyproject.toml ]
        additional_dependencies: [ toml ]
        types: [ python ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ --skip, "B321,B402", "-iii", "-ll" ]
        additional_dependencies: [ toml ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ --max-line-length=120 ]
        additional_dependencies: [
          flake8-bugbear,
          flake8-comprehensions,
          flake8-mutable,
          flake8-print,
          flake8-simplify,
        ]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      exclude: "migrations/*"
      additional_dependencies: [
        'types-pytz'
      ]
